AREA = ['physics', 'semantics', 'abstraction', 'memory']
REASONING = ['descriptive', 'counterfactual', 'explanatory', 'predictive']
TAG = ['motion', 'place recognition', 'action counting', 'spatial relations',
       'object recognition', 'action recognition', 'distractor action',
       'distractor object', 'state recognition', 'object counting',
       'change detection', 'sequencing', 'task completion',
       'adversarial action', 'collision', 'object attributes',
       'pattern breaking', 'feature matching', 'pattern discovery',
       'part recognition', 'material', 'event recall', 'containment',
       'occlusion', 'solidity', 'object permanence', 'colour recognition',
       'conservation', 'quantity', 'event counting', 'language',
       'visual discrimination', 'general knowledge', 'stability']

TAG_AREA = {
    'change detection': 'memory',
    'event recall': 'memory',
    'sequencing': 'memory',
    'visual discrimination': 'memory',
    'action counting': 'abstraction',
    'event counting': 'abstraction',
    'feature matching': 'abstraction',
    'object counting': 'abstraction',
    'pattern breaking': 'abstraction',
    'pattern discovery': 'abstraction',
    'collision': 'physics',
    'conservation': 'physics',
    'containment': 'physics',
    'material': 'physics',
    'motion': 'physics',
    'occlusion': 'physics',
    'object attributes': 'physics',
    'object permanence': 'physics',
    'quantity': 'physics',
    'solidity': 'physics',
    'spatial relations': 'physics',
    'stability': 'physics',
    'action recognition': 'semantics',
    'adversarial action': 'semantics',
    'colour recognition': 'semantics',
    'distractor action': 'semantics',
    'distractor object': 'semantics',
    'general knowledge': 'semantics',
    'language': 'semantics',
    'object recognition': 'semantics',
    'part recognition': 'semantics',
    'place recognition': 'semantics',
    'state recognition': 'semantics',
    'task completion': 'semantics',
}

CAT = AREA + REASONING + TAG